# apiVersion: v1
# kind: ConfigMap
# metadata:
#   annotations:
#       argocd.argoproj.io/sync-wave: "1"
#   name: environment-variables
#     namespace: quotes-network-policiy
# data:
#   VITE_BACKEND_URL: "http://quotes-backend.quotes.svc.cluster.local/quote"
# binaryData: {}
# immutable: false
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: default-admin
  namespace: quotes
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quotes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-pre-hook
  namespace: quotes
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
      - name: pre-sync
        image: quay.io/openshift/origin-cli:latest
        command: ["sh", "-c"]
        args:
          - >
            URL=$(oc get route quotes-backend -o jsonpath='{.spec.host}');
            oc create configmap environment-variables --from-literal=VITE_BACKEND_URL="https://$URL/quote" --dry-run=client -o yaml | oc apply -f -
      restartPolicy: Never
