---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "0"
  labels:
    kubernetes.io/metadata.name: openshift-opentelemetry-operator
    openshift.io/cluster-monitoring: "true"
  name: openshift-opentelemetry-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "1"
  name: openshift-opentelemetry-operator
  namespace: openshift-opentelemetry-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "2"
  labels:
    operators.coreos.com/opentelemetry-product.openshift-opentelemetry-operator: ''
  name: opentelemetry-product
  namespace: openshift-opentelemetry-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
#  startingCSV: opentelemetry-operator.v0.93.0-3