---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: dev
  namespace: observability
spec:
  serviceAccount: otel-collector-sidecar
  mode: sidecar
  config: |

    receivers:
      jaeger:
        protocols:
          thrift_binary:
          thrift_compact:
          thrift_http:
          grpc:
      otlp:
        protocols:
          grpc:
          http:

    processors:

    exporters:
      logging:
      otlp:
        endpoint: "tempo-simplest-gateway.observability.svc.cluster.local:8090"
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "dev"

    service:
      extensions: 
        - bearertokenauth
      pipelines:
        traces:
          receivers: 
            - otlp
            - jaeger
          exporters: 
            - otlp
            - logging