apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 02_opentelemetry-serviceaccount.yaml
- 03_opentelemetry-roles.yaml
- 04_opentelemetry-collector.yaml
- 05_opentelemetry-instrumentator.yaml
- 06_opentelemetry-rbac.yaml
