apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "0"
  labels:
    operators.coreos.com/rhtas-operator.openshift-operators: ''
  name: rhtas-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhtas-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
#  startingCSV: rhtas-operator.v1.0.1