---
kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: sonardb
  namespace: sonarqube
data:
  database-name: c29uYXI=
  database-password: UGhFS05HMFJlamJxSnQyOA==
  database-user: dXNlcmRseHd1ZDQ3
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: sonar-ldap-bind-dn
  namespace: sonarqube
data:
  password: ''
  username: Y249RGlyZWN0b3J5IE1hbmFnZXI=
type: kubernetes.io/basic-auth
