apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonardb
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
