---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "4"
  name: dev
  namespace: {{ .Values.namespace }}
spec:
  serviceAccount: otel-collector-sidecar
  mode: sidecar
  config: |
    serviceAccount: otel-collector-sidecar
    receivers:
      jaeger:
        protocols:
          thrift_compact:
          thrift_http:
    
    processors: {}

    exporters:
      otlp:
        endpoint: "tempo-simplest-gateway.observability.svc.cluster.local:8090"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          exporters: [otlp]

