apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-odf
  namespace: observability
type: Opaque
stringData:
  name: tempostack-dev-odf
  bucket: #tempostack-dev-odf-hash
  endpoint: s3.openshift-storage.svc:80
  access_key_id: #id
  access_key_secret: #secret
