apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-odf
  namespace: observability
type: Opaque
stringData:
  name: tempostack-dev-odf
  bucket: #retrieve from the ObjectBucketClaim called tempostack-dev-odf
  endpoint: s3.openshift-storage.svc:80
  access_key_id: #retrieve from the noobaa/odf/aws secret
  access_key_secret: #retrieve from the noobaa/odf/aws secret
