apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-odf
  namespace: observability
type: Opaque
stringData:
  name: tempostack-dev-odf
  bucket: tempostack-dev-odf-b91a7506-8289-4a3e-bd74-dec5d1fb9cbe
  endpoint: s3.openshift-storage.svc:80
  access_key_id: wmSvsLwdAWFrFWpaRC6g
  access_key_secret: R8yZ7x/wLkZ84zOVI7D9m6qBDFg3Onu96BdsJ836
