apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 00_quotes-namespace.yaml
- secure-pipeline/
- secure-pipeline-tasks/
