---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: quotes-network-policy-rbac
  namespace: quotes-network-policy
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quotes-network-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-pre-hook
  namespace: quotes-network-policy
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
      - name: pre-sync
        image: quay.io/openshift/origin-cli:latest
        command: ["sh", "-c"]
        args:
          - >
            URL=$(oc get route quotes-serverless-backend -n quotes-network-policy -o jsonpath='{.spec.host}');
            oc create configmap environment-variables --from-literal=VITE_BACKEND_URL="https://$URL/quote" --dry-run=client -o yaml | oc apply -f -
      restartPolicy: Never
