apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
  namespace: quotes-network-policy
spec:
  podSelector: 
    app: quotes-serverless-backend-00001
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0