apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 00_quotes-namespace.yaml
- 01_quotes-configmap.yaml
- 02_quotes-serverless-backend.yaml
- 03_quotes_frontend-deployment.yaml
- 04_quotes-service.yaml
- 05_quotes-route.yaml