---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: default-admin
  namespace: quotes-serverless
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quotes-serverless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-pre-hook
  namespace: quotes-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  template:
    spec:
      containers:
      - name: pre-sync
        image: quay.io/openshift/origin-cli:latest
        command: ["sh", "-c"]
        args:
          - >
            URL=$(oc get route.serving.knative.dev/quotes-serverless -n quotes-network-policy -o jsonpath='{.status.url}');
            oc create configmap environment-variables --from-literal=VITE_BACKEND_URL="$URL/quote" --dry-run=client -o yaml | oc apply -f -      
        restartPolicy: Never
