---
apiVersion: v1
kind: Service
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/part-of: quotes-demo
    app.kubernetes.io/name: quotes-backend-service
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: quotes-aws-dev
    app.kubernetes.io/environment: development
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}