apiVersion: batch/v1
kind: Job
metadata:
  name: configmap-pre-hook
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      containers:
      - name: pre-sync
        image: quay.io/openshift/origin-cli:latest
        command: ["sh", "-c"]
        args:
          - >
            URL=$(oc get route {{ .Values.backend.name }} -o jsonpath='{.spec.host}');
            oc create configmap {{ .Values.configmap.environmentVariables.name }} --from-literal=VITE_BACKEND_URL="https://$URL/quote\"}" --dry-run=client -o yaml | oc apply -f -
      restartPolicy: Never
