apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: quotes-instrumentation
spec:
  env:
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "20"
  exporter:
    endpoint: http://otel-collector.quotes-telemetry.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
    - b3multi
    - jaeger
    - ottrace
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    env:
    - name: OTEL_JAVAAGENT_DEBUG
      value: "true"