apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- acs-deploy-check.yaml
- acs-image-check.yaml
- acs-image-scan.yaml
- buildah.yaml
- rekor-signed-provenance.yaml
- resync.yaml
- scan-code.yaml
- scan-export-sbom.yaml
- update-deployment.yaml
- verify-commit.yaml
- verify-enterprise-contract.yaml
